### ISSUE TITLE
Doesn't compile using Python 3.5.1 Build 1

### ISSUE THREAD

**Issue by 31z4** [pybee/Python-iOS-template#10]
Gives the following error and warnings

```
/Users/e1z4/Projects/iOS/callisto/main.m:31:24: error: implicit declaration of function '_Py_char2wchar' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        wpython_home = _Py_char2wchar([python_home UTF8String], NULL);
                       ^
/Users/e1z4/Projects/iOS/callisto/main.m:31:22: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
        wpython_home = _Py_char2wchar([python_home UTF8String], NULL);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/e1z4/Projects/iOS/callisto/main.m:54:24: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
        python_argv[0] = _Py_char2wchar(main_script, NULL);
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/e1z4/Projects/iOS/callisto/main.m:56:28: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
            python_argv[i] = _Py_char2wchar(argv[i], NULL);
                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.
```

Xcode Version 7.3 (7D175)

**Comment by freakboy3742** [comment]
I'm aware of this problem - however, if you're using the 3.5 branch of the template, it [should be fixed](https://github.com/pybee/Python-iOS-template/blob/3.5/%7B%7B%20cookiecutter.dir_name%20%7D%7D/%7B%7B%20cookiecutter.app_name%20%7D%7D/main.m#L31) - references to `_Py_char2wchar` have been replaced with the equivalent call to `Py_DecodeLocale`.

Can you confirm that you were using the 3.5 branch template?

**Comment by 31z4** [comment]
Sorry, I didn't notice the branch. I was using `master`. I bet it will work on `3.5`. Thanks!

**Comment by SKrotkih** [comment]
I have the same errors and warnings with the Python.framework 2.7.
I tried all brunches (with _Py_char2wchar the same errors)
Xcode Version 7.3.1 (7D1014)

/Python_iOS/EventRegistry/main.m:31:24: error: implicit declaration of function 'Py_DecodeLocale' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        wpython_home = Py_DecodeLocale([python_home UTF8String], NULL);
                       ^
/Python_iOS/EventRegistry/main.m:31:22: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
        wpython_home = Py_DecodeLocale([python_home UTF8String], NULL);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Python_iOS/EventRegistry/main.m:32:26: warning: incompatible pointer types passing 'wchar_t *' (aka 'int *') to parameter of type 'char *' [-Wincompatible-pointer-types]
        Py_SetPythonHome(wpython_home);
                         ^~~~~~~~~~~~
In file included from /Users/oldman/Development/Python_iOS/EventRegistry/main.m:8:
In file included from /Users/oldman/Development/Python_iOS/Python.framework/Headers/Python.h:127:
/Python_iOS/Python.framework/Headers/pythonrun.h:25:41: note: passing argument to parameter here
PyAPI_FUNC(void) Py_SetPythonHome(char *);
                                        ^
/Python_iOS/EventRegistry/main.m:52:23: error: implicit declaration of function 'PyMem_RawMalloc' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        python_argv = PyMem_RawMalloc(sizeof(wchar_t*) * argc);
                      ^
/Users/oldman/Development/Python_iOS/EventRegistry/main.m:52:21: warning: incompatible integer to pointer conversion assigning to 'wchar_t **' (aka 'int **') from 'int' [-Wint-conversion]
        python_argv = PyMem_RawMalloc(sizeof(wchar_t*) * argc);
                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Python_iOS/EventRegistry/main.m:54:24: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
        python_argv[0] = Py_DecodeLocale(main_script, NULL);
                       ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Python_iOS/EventRegistry/main.m:56:28: warning: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Wint-conversion]
            python_argv[i] = Py_DecodeLocale(argv[i], NULL);
                           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/oldman/Development/Python_iOS/EventRegistry/main.m:59:29: warning: incompatible pointer types passing 'wchar_t **' (aka 'int **') to parameter of type 'char **' [-Wincompatible-pointer-types]
        PySys_SetArgv(argc, python_argv);
                            ^~~~~~~~~~~
/Python_iOS/EventRegistry/main.m:8:
In file included from /Python_iOS/Python.framework/Headers/Python.h:129:
/Python_iOS/Python.framework/Headers/sysmodule.h:13:44: note: passing argument to parameter here
PyAPI_FUNC(void) PySys_SetArgv(int, char **);
                                           ^
/Python_iOS/EventRegistry/main.m:100:9: error: implicit declaration of function 'PyMem_RawFree' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        PyMem_RawFree(wpython_home);
        ^
